---
kind: PersistentVolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /data1/k8s_nfs/katib-mysql
    server: store03
apiVersion: v1
metadata:
  name: katib-mysql
---
kind: PersistentVolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /data1/k8s_nfs/metadata-mysql
    server: store03
apiVersion: v1
metadata:
  name: metadata-mysql
---
kind: PersistentVolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /data1/k8s_nfs/minio-pv
    server: store03
apiVersion: v1
metadata:
  name: minio-pv
---
kind: PersistentVolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /data1/k8s_nfs/mysql-pv
    server: store03
apiVersion: v1
metadata:
  name: mysql-pv