apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  kustomize.component: pytorch-operator
images:
  - name: demotto/mykubeflow.gcr.io.kubeflow-images-public.pytorch-operator
    newName: demotto/mykubeflow.gcr.io.kubeflow-images-public.pytorch-operator
    newTag: v1.0.0-rc.0
