kind: PersistentVolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /hallo/hi/$(minioPvName)
    server: fucking
apiVersion: v1
metadata:
  name: $(minioPvName)
