kind: PersistentVolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /data1/k8s_nfs/$(minioPvName)
    server: store03
apiVersion: v1
metadata:
  name: $(minioPvName)
