apiVersion: v1
kind: PersistentVolume
metadata:
    name: your_pv_name
spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: your_nfs_path
      server: your_nfs_server